//MUDANÇA DE IMAGEM PRODUTO 1
const produto1D4 = document.getElementById ("produto1D4") ;
produto1D4.addEventListener ("mouseover", function () {
produto1D4.src = "./produtos/D4-GULF CINZA FRENTE.jpg";
})
produto1D4.addEventListener ("mouseout", function () {
produto1D4.src = "./produtos/D4-GULF CINZA COSTAS.jpg" ;
})

//MUDANÇA DE IMAGEM PRODUTO 2
//const produto2D4 = document.getElementById ("produto2D4") ;
//produto2D4.addEventListener ("mouseover", function () {
//produto2D4.src = "#";
//})
//produto2D4.addEventListener ("mouseout", function () {
//produto2D4.src = "#"
//})

//MUDANÇA DE IMAGEM PRODUTO 3
const produto3D4 = document.getElementById ("produto3D4") ;
produto3D4.addEventListener ("mouseover", function () {
produto3D4.src = "./produtos/D4-MARTINI OW FRENTE.jpg";
})
produto3D4.addEventListener ("mouseout", function () {
produto3D4.src = "./produtos/D4-MARTINI OW COSTAS.jpg" ;
})

//MUDANÇA DE IMAGEM PRODUTO 2
//const produto4D4 = document.getElementById ("produto4D4") ;
//produto4D4.addEventListener ("mouseover", function () {
//produto4D4.src = "#";
//})
//produto4D4.addEventListener ("mouseout", function () {
//produto4D4.src = "#"
//})

//MUDANÇA DE IMAGEM PRODUTO 5
//const produto5D4 = document.getElementById ("produto5D4") ;
//produto5D4.addEventListener ("mouseover", function () {
//produto5D4.src = "#";
//})
//produto5D4.addEventListener ("mouseout", function () {
//produto5D4.src = "#"
//})