//MUDANÇA DE IMAGEM PRODUTO 1
const produto1D4 = document.getElementById ("produto1D4") ;
produto1D4.addEventListener ("mouseover", function () {
produto1D4.src = "./PRODUTOS D4 (FUNDO BRANCO)/D4 GULF PRETA FRENTE.jpeg";
})
produto1D4.addEventListener ("mouseout", function () {
produto1D4.src = "./PRODUTOS D4 (FUNDO BRANCO)/D4 GULF PRETA COSTAS.jpeg" ;
})

//MUDANÇA DE IMAGEM PRODUTO 2
const produto2D4 = document.getElementById ("produto2D4") ;
produto2D4.addEventListener ("mouseover", function () {
produto2D4.src = "./PRODUTOS D4 (FUNDO BRANCO)/D4 BÁSICA PRETA COSTAS.jpeg";
})
produto2D4.addEventListener ("mouseout", function () {
produto2D4.src = "/PRODUTOS D4 (FUNDO BRANCO)/D4 BÁSICA PRETA FRENTE.jpeg"
})

//MUDANÇA DE IMAGEM PRODUTO 3
const produto3D4 = document.getElementById ("produto3D4") ;
produto3D4.addEventListener ("mouseover", function () {
produto3D4.src = "../PRODUTOS D4 (FUNDO BRANCO)/D4 MARTINI PRETA FRENTE.jpeg";
})
produto3D4.addEventListener ("mouseout", function () {
produto3D4.src = "./PRODUTOS D4 (FUNDO BRANCO)/D4 MARTINI PRETA COSTAS.jpeg" ;
})

//MUDANÇA DE IMAGEM PRODUTO 4
const produto4D4 = document.getElementById ("produto4D4") ;
produto4D4.addEventListener ("mouseover", function () {
produto4D4.src = "./PRODUTOS D4 (FUNDO BRANCO)/D4 MICHELIN PRETA COSTAS.jpeg";
})
produto4D4.addEventListener ("mouseout", function () {
produto4D4.src = "./PRODUTOS D4 (FUNDO BRANCO)/D4 MICHELIN PRETA FRENTE.jpeg"
})

//MUDANÇA DE IMAGEM PRODUTO 5
const produto5D4 = document.getElementById ("produto5D4") ;
produto5D4.addEventListener ("mouseover", function () {
produto5D4.src = "./PRODUTOS D4 (FUNDO BRANCO)/D4 PICA FUMO PRETA COSTAS.jpeg";
})
produto5D4.addEventListener ("mouseout", function () {
produto5D4.src = "./PRODUTOS D4 (FUNDO BRANCO)/D4 PICA FUMO PRETA FRENTE.jpeg"
})